### ISSUE TITLE
App Crashes when all cards are gone

### ISSUE THREAD

**Issue by KartikayKK** [MostafaGazar/StackView#1]
App is crashing when all cards are gone and empty space is clicked . Need Help for a loop or cards stop going after the last one.

**Comment by MostafaGazar** [comment]
Thanks Kartikay for using StackView. 

Here is an example of what you can do when the user go through all the available cards.
```kotlin
        stackView.onChangeListener = object : OnChangeListener {
            override fun onChange(remainingCardsCount: Int, totalCardsCount: Int) {
                if (remainingCardsCount == 0) {
                    activity?.finish()

                    return
                }
            }
        }
```

Another option would be to modify your `Adapter` to cycle through the items in the StackView.
